### ISSUE TITLE
ssh connection in jsdocker warnings

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#139] opened 2015-09-20 11:56 UTC
root@kds1:~# jsdocker new -n aysdevel -p js007 --start
WARNING: no system redis found (port 9999, needs to be installed as instance 'system').
create:aysdevel
SSH PORT WILL BE ON:9024
MAP:
 /opt/code            /opt/code
 /tmp/dockertmp/aysdevel /tmp
 /var/jumpscale       /var/docker/aysdevel
install docker with name 'despiegk/mc'
test docker internal port:22 on ext port:9024
connect ssh2
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/opt/jumpscale7/lib/paramiko/transport.py", line 1582, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/opt/jumpscale7/lib/paramiko/transport.py", line 1709, in _check_banner
ERROR:paramiko.transport:    raise SSHException('Error reading SSH protocol banner' + str(e))
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/opt/jumpscale7/lib/paramiko/transport.py", line 1582, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/opt/jumpscale7/lib/paramiko/transport.py", line 1709, in _check_banner
ERROR:paramiko.transport:    raise SSHException('Error reading SSH protocol banner' + str(e))
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/opt/jumpscale7/lib/paramiko/transport.py", line 1582, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/opt/jumpscale7/lib/paramiko/transport.py", line 1709, in _check_banner
ERROR:paramiko.transport:    raise SSHException('Error reading SSH protocol banner' + str(e))
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
ERROR:paramiko.transport:
connect ssh2

**Comment by Hamdy** [comment] 2015-10-28 09:25
Can't reproduce .. closing.

root@js:/opt/jumpscale7/apps/portals/main/base/home# jsdocker new -n aysdevel -p js007 --start
create:aysdevel
SSH PORT WILL BE ON:9022
MAP:
 /opt/code            /opt/code
 /tmp/dockertmp/aysdevel /tmp
 /var/jumpscale       /var/docker/aysdevel
download docker
Pulling repository despiegk/mc
67a1ca35cb69: Download complete 
511136ea3c5a: Download complete 
fe95bf7d5f50: Download complete 
9a4594fe74ea: Download complete 
8c4b1edcceea: Download complete 
ed5a78b7b42b: Download complete 
ed20311f4e37: Download complete 
566cb658675c: Download complete 
264f67d8d411: Download complete 
ec032a213a18: Download complete 
Status: Downloaded newer image for despiegk/mc:latest
install docker with name 'despiegk/mc'
test docker internal port:22 on ext port:9022
Generating public/private dsa key pair.
Created directory '/root/.ssh'.
Your identification has been saved in /root/.ssh/id_dsa.
Your public key has been saved in /root/.ssh/id_dsa.pub.
The key fingerprint is:
9a:41:d1:60:63:81:c4:e7:2b:ac:a4:00:ca:1b:a9:2b root@js
The key's randomart image is:
+--[ DSA 1024]----+
|   o..B+         |
|    oo.o.        |
|     o.          |
|.    ..          |
|+ ..  ..S        |
|o+. o .+         |
|ooo. .o          |
|E..              |
|o.               |
+-----------------+
connect ssh2
root@js:/opt/jumpscale7/apps/portals/main/base/home#

**Closed by Hamdy** 2015-10-28 09:25 UTC
Labels: bug, Normal
